language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra

before_install:
    - yes | sdkmanager "platforms;android-28"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
