language: android
dist: trusty
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
